<?php
declare(strict_types=1);

return [
    'GET' => [
        '/'                  => ['Controllers\\AuthController', 'root'],
        '/login'             => ['Controllers\\AuthController', 'login'],
        '/login.php'         => ['Controllers\\AuthController', 'legacyLogin'],
        '/dashboard'         => ['Controllers\\DashboardController', 'index'],
        '/packages'          => ['Controllers\\PackageController', 'index'],
        '/inventory'         => ['Controllers\\InventoryController', 'index'],
        '/distributors'      => ['Controllers\\DistributorController', 'index'],
        '/distributors/show' => ['Controllers\\DistributorController', 'show'],
        '/sales'             => ['Controllers\\SaleController', 'index'],
        '/sales/receipt'     => ['Controllers\\SaleController', 'receipt'],
        '/payments'          => ['Controllers\\PaymentController', 'index'],
        '/payments/receipt'  => ['Controllers\\PaymentController', 'receipt'],
        '/lines'             => ['Controllers\\LineController', 'index'],
        '/line-payments'     => ['Controllers\\LineController', 'payments'],
        '/expenses'          => ['Controllers\\ExpenseController', 'index'],
        '/owner-withdrawals' => ['Controllers\\CashController', 'withdrawals'],
        '/cash'              => ['Controllers\\CashController', 'index'],
        '/reports'           => ['Controllers\\ReportController', 'index'],
        '/search'            => ['Controllers\\ReportController', 'search'],
        '/audit'             => ['Controllers\\SettingsController', 'audit'],
        '/settings'          => ['Controllers\\SettingsController', 'index'],
        '/backup'            => ['Controllers\\SettingsController', 'backup'],
    ],
    'POST' => [
        '/login'              => ['Controllers\\AuthController', 'login'],
        '/logout'              => ['Controllers\\AuthController', 'logout'],
        '/packages/store'     => ['Controllers\\PackageController', 'store'],
        '/packages/update'    => ['Controllers\\PackageController', 'update'],
        '/packages/delete'    => ['Controllers\\PackageController', 'delete'],
        '/inventory/store'    => ['Controllers\\InventoryController', 'store'],
        '/inventory/edit'     => ['Controllers\\InventoryController', 'edit'],
        '/inventory/delete'   => ['Controllers\\InventoryController', 'delete'],
        '/distributors/store' => ['Controllers\\DistributorController', 'store'],
        '/distributors/delete'=> ['Controllers\\DistributorController', 'delete'],
        '/sales/store'        => ['Controllers\\SaleController', 'store'],
        '/sales/update'       => ['Controllers\\SaleController', 'update'],
        '/sales/delete'       => ['Controllers\\SaleController', 'delete'],
        '/payments/store'     => ['Controllers\\PaymentController', 'store'],
        '/payments/update'    => ['Controllers\\PaymentController', 'update'],
        '/payments/delete'    => ['Controllers\\PaymentController', 'delete'],
        '/lines/store'        => ['Controllers\\LineController', 'store'],
        '/lines/update'       => ['Controllers\\LineController', 'update'],
        '/lines/delete'       => ['Controllers\\LineController', 'delete'],
        '/line-payments/store'=> ['Controllers\\LineController', 'storePayment'],
        '/line-payments/update'=> ['Controllers\\LineController', 'updatePayment'],
        '/line-payments/delete'=> ['Controllers\\LineController', 'deletePayment'],
        '/expenses/store'     => ['Controllers\\ExpenseController', 'store'],
        '/expenses/update'    => ['Controllers\\ExpenseController', 'update'],
        '/expenses/delete'    => ['Controllers\\ExpenseController', 'delete'],
        '/owner-withdrawals/store'  => ['Controllers\\CashController', 'storeWithdrawal'],
        '/owner-withdrawals/update' => ['Controllers\\CashController', 'updateWithdrawal'],
        '/owner-withdrawals/delete' => ['Controllers\\CashController', 'deleteWithdrawal'],
        '/settings/password'  => ['Controllers\\SettingsController', 'changePassword'],
        '/backup/create'      => ['Controllers\\SettingsController', 'createBackup'],
        '/backup/restore'     => ['Controllers\\SettingsController', 'restore'],
    ],
];
